import "./globals.css";
import { Lexend_Deca } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const lexed = Lexend_Deca({
  subsets: ["latin"],
  display: "swap",
  variable: '--font-lexed',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={lexed.className}>
      <body>
        <main className="min-h-screen bg-background flex flex-col items-center">
          {children}
        </main>
      </body>
    </html>
  );
}
